version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 545101823957.dkr.ecr.us-east-2.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=$COMMIT_HASH
      - echo "Using IMAGE_TAG: $IMAGE_TAG"

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t 545101823957.dkr.ecr.us-east-2.amazonaws.com/my-new-app:$IMAGE_TAG .
      - docker tag 545101823957.dkr.ecr.us-east-2.amazonaws.com/my-new-app:$IMAGE_TAG 545101823957.dkr.ecr.us-east-2.amazonaws.com/my-new-app:latest

  post_build:
    commands:
      - echo "Pushing Docker images..."
      - docker push 545101823957.dkr.ecr.us-east-2.amazonaws.com/my-new-app:$IMAGE_TAG
      - docker push 545101823957.dkr.ecr.us-east-2.amazonaws.com/my-new-app:latest
      - echo "Writing imagedefinitions.json..."
      - printf '[{"name":"my-app-container","imageUri":"545101823957.dkr.ecr.us-east-2.amazonaws.com/my-new-app:%s"}]' $IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
